name: css-compile-successfully

run-name: '${{ github.actor }} is compiling the CSS! ğŸ’…ğŸ¼'

on:
  pull_request:
    branches: ['main', 'release/**']
    types: [opened, synchronize]
    paths: ['packages/**']

jobs:
  check-compile-css:
    runs-on: ubuntu-22.04

    steps:
      - name: 'Checkout ğŸ”'
        uses: actions/checkout@v4

      - name: 'Cache dependencies ğŸ“¦'
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          paths: 'node_modules'
          key: ${{ runner.os }}-node_module-${{ hashFiles('package*.json') }}-${{ hashFiles('.github/workflows/css-compile-successfully.yml') }}

      - name: 'Setup node âš™ï¸'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
            
      - name: 'Install dependencies â®‹'
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci --workspace=packages

      - name: 'Build SASS ğŸ«¶ğŸ¼'
        run: npm run build --workspace=packages
