name: to-check-css-compile-successfully
on:
  pull_request:
    branches: ['main', 'release/**']
    types: [opened, synchronize]
    paths: ['packages/**']
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous runs âŒ
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout ğŸ”
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache dependencies ğŸ“¦
        uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('.github/workflows/to-check-css-compile-successfully.yml') }}

      - name: Setup node âš™ï¸
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies â¬‡ï¸
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          npm install -g sass
          npm install --workspace=packages

      - name: Build Sass ğŸ«¶ğŸ¼
        run: npm run build --workspace=packages
